export const SET_PLAYING_STATE = "SET_PLAYING_STATE";
export const SET_FULL_SCREEN = "SET_FULL_SCREEN";
export const SET_PLAYLIST = "SET_PLAYLIST";
export const SET_PLAY_MODE = "SET_PLAY_MODE";
export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const SET_SEQUENCE_LIST = "SET_SEQUENCE_LIST";
export const SET_SONG_DETAIL_BY_MUSIC_ID = "SET_SONG_DETAIL_BY_MUSIC_ID";
// 获取推荐歌手
export const SET_RECOMMEND_SINGER = "SET_RECOMMEND_SINGER";
// 根据歌手id查询歌曲
export const SET_SONG_DETAIL_BY_SINGER_ID = "SET_SONG_DETAIL_BY_SINGER_ID";

// 获取歌曲排行榜列表
export const SET_SONG_LIST_RANK = "SET_SONG_LIST_RANK";
// 根据关键字查询各类排行榜下的歌曲
export const SET_SONGS_BY_RANK = "SET_SONGS_BY_RANK";